### ISSUE TITLE
Is it open source ?

### ISSUE THREAD

**Issue by tennessine** [VickyAgravat/wp-codemirror-block#1]
I want to modify some ui

**Comment by tennessine** [comment]
I found blocks.build.js not the source code

**Comment by VickyAgravat** [comment]
Thank you very much for your interest.
How can i help you?

**Comment by tennessine** [comment]
@VickyAgravat  I need your source code to have some modification, I want to run the code on docker and return the result to user.

**Comment by tennessine** [comment]
I also sent an email to you , vicky.agravat@g***l.com

**Comment by tennessine** [comment]
Could you upload all the source here?

**Comment by VickyAgravat** [comment]
Now, all code is available on github. you can modify it as you want.
