### ISSUE TITLE
Run/Execute button is not showing

### ISSUE THREAD

**Issue by kbepari52** [VickyAgravat/wp-codemirror-block#2]
after update the plugin, today I recognized that the run button is missing or may be disabled

**Comment by VickyAgravat** [comment]
Yes, Due to Cross-Site Scripting issue, Code Execution functionality (beta functionality) removed.

It is also clearly mentioned on change log.
You can get more details about issue here: https://github.com/advisories/GHSA-f949-cfvp-v3rg

**Comment by kbepari52** [comment]
So, can we get back the run button in future ?
