### ISSUE TITLE
Can support for the rainbow bracket feature be considered?

### ISSUE THREAD

**Issue by TheWhiteDog9487** [VickyAgravat/wp-codemirror-block#4]
In actual code display, there are usually a lot of brackets, which lead to poor readability. Coloring the brackets can significantly improve this problem.
I wonder if you have the intention to create this function?

Also, thank you so much for making this plugin, it's really great.

**Comment by VickyAgravat** [comment]
Actually, this plugin is wrapper on codemirror library for wordpress block functionality.

So, you can ask this feature in their original repo https://github.com/codemirror/codemirror5/issues.
If they provided this feature. I will definitely include it in next feature update.
